language: node_js
node_js:
  - "node"
  - "6"
script: npm run lint
deploy:
  provider: npm
  email: trevordmiller@icloud.com
  api_key:
    secure: OvK6xwe4Lqu+FDSeqPgUIN/cLk8XEaPrbusBZrmqEEf86g6M3g8pUNmbCIihbYVQY4E8tFNasrMHZXylaehAu0EaFjwwui+F/GHn2NtjdP8CbF8iX+c0dF3dSzipoXyaKJ5K6J63H9Z4zWQFFAA72nBtlka9u8GkSuIV+wxhUdM4aNzc3xMgSgPP69VH0hh8J89Ve2NA333PHwvdCHtCTwc7vrO82KBjFSHY2dOe1tg7Dh5S8UXMoFWLwXZ35T5p7TLBHufHa1Pv6G1IPa5QPRRLcNUSAsQBxgaimz0uPCko9xQnCzYAAtchFdRARrOYvO3T7ivfv8unfzQe6Wayrj07UyVnI+8afZPVBUSN2qn1UViHzuuSNAhL9xtGjz9O2Xp/MPJ7TOHiRFssDbIffqfnOZMfzaIJg5W+auHAKaWSM+8u7ewKOB0XQubTIAIqEdECuIaTXsMTDosLsZ5U3gFZJYB5xizDnWSbnqzutGfxiexlYEFLMyvz0mO4WrtsYuDYNkzuVon2//fCcqdrJp4mormrnjcuQzS3yvLh5so8XMiTkerNgiy7WTKMP6hPtEMOnZM4Tbm8lte6Wtyzx2/C6QzZn80nTFjmKnQ2aeQ66LGiKNQfdSe8iqgdUkxrHXOX84pOTgd4yR50bWz0WUBeYRk8oUChBaG/atix4ao=
  on:
    repo: trevordmiller/nova-hyperterm
    branch: master
